version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    target-branch: main
    schedule:
      interval: weekly
      day: sunday
      time: "12:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 2
    reviewers:
      - mintak21
